### PR TITLE
to reflect advances on main project

### PR DESCRIPTION
**Pull request by toofun666**

### CODE REVIEW

**Comment by toofun666** [comment]
@pdvyas can you process this PR please?

**Comment by toofun666** [comment]
@hsoft is it possible that you process this PR?

**Comment by hsoft** [comment]
@toofun666 no. I have nothing to do with the "frappe" project.

**Comment by toofun666** [comment]
@pdvyas you need to process this for ErpNext...

**Comment by pdvyas** [comment]
@toofun666 My changes were merged upstream and so frappe uses the upstream version. https://github.com/frappe/frappe/blob/develop/requirements.txt#L28

I haven't been involved with Frappe/ERPNext for ~2years now. Maybe all you need to do is bump the pinned version in frappe's requirements.txt

\cc @rmehta this repo should probably be deleted.

**Comment by rmehta** [comment]
Updated https://github.com/frappe/frappe/pull/4099

Will remove this repo.

**Pull request closed without merging**
